CREATE TABLE ORDEM_SERVICO (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	CLIENTE_ID BIGINT NOT NULL,
	DESCRICAO TEXT NOT NULL,
	PRECO DECIMAL(10,2) NOT NULL,
	STATUS VARCHAR(20) NOT NULL,
	DATA_ABERTURA DATETIME NOT NULL,
	DATA_FINALIZACAO DATETIME,
	
	PRIMARY KEY (ID)
);

ALTER TABLE ORDEM_SERVICO ADD CONSTRAINT FK_ORDEM_SERVICO_CLIENTE
FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (ID)